In [ ]:
# Define scalars
number_of_units = 50
mass_of_sun = 1.989e30
length_great_wall_of_china = 21196
print(number_of_units)
print(mass_of_sun)
print(length_great_wall_of_china)

50
1.989e+30
21196


In [ ]:
# importing required library (numpy as np)
import numpy as np
# creating a column vector with 2 rows and 1 column using np.array() function
col_vec = np.array([[4],[3]])
print ("A column vector\n",col_vec)
# printing the shape of the vector
print("Shape of vector=",col_vec.shape)


A column vector
 [[4]
 [3]]
Shape of vector= (2, 1)


In [ ]:
# importing required library (numpy as np)
import numpy as np
# creating a row vector with 1 row and 3 columns using np.array() function
row_vec = np.array([[4,-1,2]])
print("A row vector\n",row_vec)
# printing the shape of the vector
print("Shape of vector=",row_vec.shape)


A row vector
 [[ 4 -1  2]]
Shape of vector= (1, 3)


In [ ]:
# importing required library (numpy as np)
import numpy as np
#Illustrating a Zero row vector of dimension 3 using np.array() function
zero_vector_1=np.array([0,0,0])
print(zero_vector_1)
#Illustrating a Zero row vector of dimension 3 using np.zeros() function
zero_vector_2=np.zeros(3)
print(zero_vector_2)
#Illustrating a Zero column vector of dimension 3 using np.zeros() and reshape() function
zero_vector_3=np.zeros(3).reshape(3,-1)
print(zero_vector_3)


[0 0 0]
[0. 0. 0.]
[[0.]
 [0.]
 [0.]]


In [ ]:
# importing required library (numpy as np)
import numpy as np
#Illustrating a One vector of dimension 3 using np.array() function
one_vector_1=np.array([1,1,1])
print(one_vector_1)
#Illustrating a One vector of dimension 3 using np.ones() function
one_vector_2=np.ones(3)
print(one_vector_2)
#Illustrating a column vector of ones of dimension 3 using np.ones() and reshape() function
one_vector_3=np.ones(3).reshape(3,-1)
print(one_vector_3)


[1 1 1]
[1. 1. 1.]
[[1.]
 [1.]
 [1.]]


In [ ]:
# importing required libraries (numpy as np)
import numpy as np
vector=np.array([[4],[-1],[2]])
print("The vector\n",vector)
#Addressing a value of vector by index
print("\nElement at position 1=",vector[1])


The vector
 [[ 4]
 [-1]
 [ 2]]

Element at position 1= [-1]


In [ ]:
# importing required libraries (numpy as np)
import numpy as np
#Create a vector
vector=np.array([3,3])
#Magnitude of vector can be found using function np.linalg.norm() function
print("\nMagnitude of the vector = ",np.linalg.norm(vector))



Magnitude of the vector =  4.242640687119285


In [ ]:
# importing required libraries (numpy as np)
import numpy as np
# Creating matrices of various dimension using np.array() function
matrix_2x2 = np.array([[1, 2],
                       [3, 4]])
matrix_3x3 = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [8, 9, 10]])
print("2x2 Matrix\n",matrix_2x2,"\nshape of matrix -> ",matrix_2x2.shape)
print("\n3x3 Matrix\n",matrix_3x3,"\nshape of matrix -> ",matrix_3x3.shape)


2x2 Matrix
 [[1 2]
 [3 4]] 
shape of matrix ->  (2, 2)

3x3 Matrix
 [[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]] 
shape of matrix ->  (3, 3)


In [ ]:
# importing required libraries (numpy as np)
import numpy as np
# Creating a 3x2 Matrix "A"
A = np.array([[3,-1],[2,-2],[3,1],[1,4]])
#selecting an element at row index 2 and column index 1
print("Element of matrix A at index position [2,1] is", A[2,1])


Element of matrix A at index position [2,1] is 1


In [ ]:
# importing required libraries (numpy as np)
import numpy as np
# Creating a 3x2 Matrix "A"
A = np.array([[2,-2],[3,1],[1,4]])
print("Matrix A:\n",A)
# Finding transpose of a matrix using the function transpose()
print("Matrix A Transpose: \n",np.transpose(A))


Matrix A:
 [[ 2 -2]
 [ 3  1]
 [ 1  4]]
Matrix A Transpose: 
 [[ 2  3  1]
 [-2  1  4]]


In [ ]:
# importing required libraries (numpy as np)
import numpy as np
# Creating a diagonal matrix with diagonal elements as (1,3,2)
diagonal_matrix = np.diag((1,3,2))
print(diagonal_matrix)
# Creating a diagonal matrix with a range of values
#np.arange(1, 7, 2): This line creates a NumPy array containing numbers generated within the range
#of 1 (inclusive) to 7 (exclusive) with a step size of 2. So, it will generate the array [1, 3, 5].
matrix_range= np.diag(np.arange(1,7,2))
print(matrix_range)

[[1 0 0]
 [0 3 0]
 [0 0 2]]
[[1 0 0]
 [0 3 0]
 [0 0 5]]


In [ ]:

# importing required libraries (numpy as np)
import numpy as np
#Creating an Identity matrix of size 2 using np.identity() function
identity_matrix_1 = np.identity(2)
print("Identity_matrix 1\n",identity_matrix_1)
#Creating an Identity matrix of size 3 using np.eye() fucntion
identity_matrix_2 = np.eye(3)
print("\nIdentity_matrix 2\n",identity_matrix_2)


Identity_matrix 1
 [[1. 0.]
 [0. 1.]]

Identity_matrix 2
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# importing required libraries (numpy as np)
import numpy as np
#Creating matrix A
A = np.array([[2,3,1],
            [3,4,-1],
            [1,-1,1]])
print("A:\n" , A)
# Finding the Transpose of the matrix
transposed_matrix = A.transpose()
print("Transpose of A:\n" , transposed_matrix)
#Comparing each element of both matrices (returns a matrix of boolean compared values) and saving it in a variable comparison
comparison = (A == transposed_matrix)
#Checking if all the elements in the matrix comparision is true
equal_arrays = comparison.all()
print(equal_arrays)
print(comparison)


A:
 [[ 2  3  1]
 [ 3  4 -1]
 [ 1 -1  1]]
Transpose of A:
 [[ 2  3  1]
 [ 3  4 -1]
 [ 1 -1  1]]
True
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
# importing required libraries (numpy as np)
import numpy as np
#Creating a lower triangular matrix
lower_triangular_matrix_1 = np.tril([[1,2,3],
                               [4,5,6],
                               [7,8,9]])
print("Lower triangular matrix\n",lower_triangular_matrix_1)


Lower triangular matrix
 [[1 0 0]
 [4 5 0]
 [7 8 9]]


In [ ]:
#for upper triangular matrix
import numpy as np
upper_triangular_matrix_1=np.triu([[1,2,3],
                                   [4,5,6],
                                   [7,8,9]])
print("upper triangular matrix\n",upper_triangular_matrix_1)

upper triangular matrix
 [[1 2 3]
 [0 5 6]
 [0 0 9]]


In [ ]:
#EXERCISE
#Create a square matrix A of order 3. Solve the following:
import numpy as np
A=([[2,3,4],
         [2,4,5],
         [5,4,6]])

In [ ]:
#1Q
#Convert A to an upper triangular matrix B
B=np.triu(A)
print(B)

[[2 3 4]
 [0 4 5]
 [0 0 6]]


In [ ]:
#2Q
#Convert B to a lower triangular matrix C
c=np.tril(B)
print(c)

[[2 0 0]
 [0 4 0]
 [0 0 6]]


In [ ]:
#3Q
#Find the transpose of matrix C
trans=np.transpose(c)
print(trans)

[[2 0 0]
 [0 4 0]
 [0 0 6]]


In [ ]:
#4Q
#Check whether matrix C is a diagonal matrix
def is_diagonal(matrix):
    return np.all(matrix - np.diag(np.diagonal(matrix)) == 0)
print(is_diagonal(c))



True


Addition of 2 vectors

In [ ]:
# importing required libraries (numpy as np)
import numpy as np
#Create 2 vectors
vector_1 = np.array([[2, -1, 1]])
vector_2 = np.array([[1, 2, -1]])

print ("1st  Vector :  ", vector_1)
print ("2nd  Vector :  ", vector_2)
# Addition of the vectors using the function np.add()
out = np.add(vector_1, vector_2)
print ("Added Vector : ", out)


1st  Vector :   [[ 2 -1  1]]
2nd  Vector :   [[ 1  2 -1]]
Added Vector :  [[3 1 0]]


Addition of 2 matrices

In [ ]:
# importing required libraries (numpy as np)
import numpy as np
# Creation of 2 matrices
matrix_1 = np.array([[10,20,30],
                     [-30,-40,-50]])
matrix_2 = np.array([[100,-200,300],
                     [30,50,70]])

print ("1st  Matrix : \n", matrix_1)
print ("2nd  Matrix : \n", matrix_2)
# Addition of the matrices using np.add() function
out = np.add(matrix_1, matrix_2)
print ("Added Matrix : \n", out)


1st  Matrix : 
 [[ 10  20  30]
 [-30 -40 -50]]
2nd  Matrix : 
 [[ 100 -200  300]
 [  30   50   70]]
Added Matrix : 
 [[ 110 -180  330]
 [   0   10   20]]


Scalar vector multiplication

In [ ]:
# importing required libraries (numpy as np)
import numpy as np
#Defining a Vector 'v' and scalar 's'
v = np.array([[2],[-1],[3]])
s = 2.5
#Scalar Vector Multiplication
vector_mul = v*s
print("Vector: \n",v,"\nScalar:",s,"\nScalar Vector multiplication:\n",vector_mul)


Vector: 
 [[ 2]
 [-1]
 [ 3]] 
Scalar: 2.5 
Scalar Vector multiplication:
 [[ 5. ]
 [-2.5]
 [ 7.5]]


Multiplication of matrix by scalar

In [ ]:
# importing required libraries (numpy as np)
import numpy as np
#Defining a matrix 'A' and scalar 's'
A = np.array([[1,2,1],
                     [-1,1,0],
                     [2,-1,1]])
print("Matrix:\n",A)
s = 2.5
print("Scalar :",s)
#Multiplication of Matrix by a Scalar
matrix_mul =  s * A
print("Multiplication of Matrix by a Scalar:\n",matrix_mul)


Matrix:
 [[ 1  2  1]
 [-1  1  0]
 [ 2 -1  1]]
Scalar : 2.5
Multiplication of Matrix by a Scalar:
 [[ 2.5  5.   2.5]
 [-2.5  2.5  0. ]
 [ 5.  -2.5  2.5]]


Inner product

In [ ]:
# importing required libraries (numpy as np)
import numpy as np
#Creating the vectors
vector_1 = np.array([1,2,3])
vector_2 = np.array([1,0,3])
print("Vector 1:\n",vector_1)
print("Vector 2:\n",vector_2)
# Finding inner product of vector of same dimensions using inner() function of the NumPy library.
inner_product_1 = np.inner(vector_1,vector_2)
print("Inner Product of Vector 1, Vector 2:\n",inner_product_1)


Vector 1:
 [1 2 3]
Vector 2:
 [1 0 3]
Inner Product of Vector 1, Vector 2:
 10


Angle b/w two vectors

In [ ]:
#import the library numpy
import numpy as np
# Function to find angle between two vectors
def angle_between(vector_1, vector_2):
    dot_pr = vector_1.dot(vector_2)
    norms = np.linalg.norm(vector_1) * np.linalg.norm(vector_2) #linalg.norm is used to find the magnitude ==> det(|a|)
    return np.rad2deg(np.arccos(dot_pr / norms))
# Create two vectors
vector_1 = np.array([3,-1,2])
vector_2 = np.array([2,4,-1])
print("v1 = ",vector_1,"\nv2 = ", vector_2)
#Find the angle between them by using the function angle_between()
print("Angle Between the vectors v1 and v2 in 'degree' is :",angle_between(vector_1, vector_2))


v1 =  [ 3 -1  2] 
v2 =  [ 2  4 -1]
Angle Between the vectors v1 and v2 in 'degree' is : 90.0


In [ ]:
#import the library numpy
import numpy as np
#Define a matrix
A =  np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("A :\n", A)
#Define a column vector
v = np.array([[1], [2], [3]])
print("v :\n", v)
# Find product of the matrix and Vector
product = np.matmul(A,v)
print("Product of A and v is: \n", product)


A :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
v :
 [[1]
 [2]
 [3]]
Product of A and v is: 
 [[14]
 [32]
 [50]]


In [ ]:
# importing required libraries (numpy as np)
import numpy as np
# Creating Matrices
A = np.array([[1, 4, 7],
            [2, 5, 8],
            [3, 6, 9]])
B = np.array([[4, 2, 3],
            [2, 0, 7],
            [1, 3, 0]])
print("A :\n", A)
print("B :\n", B)
# Multiplying A and B
result=np.matmul(A,B)
print("Matrix Multiplication: A.B :\n",result)


A :
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
B :
 [[4 2 3]
 [2 0 7]
 [1 3 0]]
Matrix Multiplication: A.B :
 [[19 23 31]
 [26 28 41]
 [33 33 51]]


In [ ]:
# importing required libraries (numpy as np)
import numpy as np
# Creating Matrix
matrix = np.array([[10, 2],
                  [5, 2]])
#Finding the determinant
print(np.linalg.det(matrix))


10.000000000000002


MATRIX INVERTION


In [ ]:
# Importing required libraries (numpy as np)
import numpy as np
# Creating Matrix A
A = np.array([[1, 2],
                   [4, 5]])
print("Matrix A:\n", A)
# Finding the inverse matrix using np.linalg.inv() function
Ainv = np.linalg.inv(A)
print('The inverse of A is:\n', Ainv)
print("Multiplication of A and Ainv is:\n", np.matmul(A, Ainv))


Matrix A:
 [[1 2]
 [4 5]]
The inverse of A is:
 [[-1.66666667  0.66666667]
 [ 1.33333333 -0.33333333]]
Multiplication of A and Ainv is:
 [[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]


ORTHOGONAL MATRIX

In [ ]:
# Importing required libraries (numpy as np)
import numpy as np
# Creating Matrix
A = np.array([[1.0,0.0],
                [0.0,1.0]])
print("A:\n", A)
#Checking for A.AT=AT.A
comparison_1 = np.dot(A.transpose(),A) == np.dot(A,A.transpose())
print(comparison_1)
#Checking for A.AT=Identity Matrix
comparison_2 =  np.dot(A.transpose(),A)== np.eye(2)
print(comparison_2)
# Comparing both the comparison done earlier
comparison_3 = comparison_1 == comparison_2
#Checking if all elements of matrix comparision are true.
equal_arrays = comparison_3.all()
print("A it an orthogonal matrix: ",equal_arrays)


A:
 [[1. 0.]
 [0. 1.]]
[[ True  True]
 [ True  True]]
[[ True  True]
 [ True  True]]
A it an orthogonal matrix:  True


RANK  OF MATRIX

In [ ]:
# Importing required libraries (numpy as np)
import numpy as np
# Creating Matrices
A = np.array([[1,1.0],[3,3]])
print('The matrix A is:\n', A)
B = np.eye(4)
print('The matrix B is:\n', B)
# Finding the rank of matrix a using np.linalg.matrix_rank() function
print(" Rank of A is:",np.linalg.matrix_rank(A))
# Finding the rank of matrix b using np.linalg.matrix_rank() function
print(" Rank of B is:",np.linalg.matrix_rank(B))


The matrix A is:
 [[1. 1.]
 [3. 3.]]
The matrix B is:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
 Rank of A is: 1
 Rank of B is: 4


Exercise

In [ ]:
import numpy as np
A=np.array([[3,-1,2],
    [1,2,3],
    [4,1,1]])

#to find det
det=np.linalg.det(A)
rank=np.linalg.matrix_rank(A)
inv=np.linalg.inv(A)

print(det,rank,inv )


-27.999999999999996 3 [[ 0.03571429 -0.10714286  0.25      ]
 [-0.39285714  0.17857143  0.25      ]
 [ 0.25        0.25       -0.25      ]]


Linear transformation

A transformation T is said to be linear, if it satisfies the following properties:

1.    T(x1 + x2) = T(x1) + T(x2)

2.    T(aX1) = aT(x1)

Where, x1 and x2 are vectors and a is a scalar.

solving system of linear equation

In [1]:
# import the library numpy
import numpy as np
#Define the coefficient matrix
matrix_1 = np.array([[1, 3, -1],
              [2, 5, 4],
              [2, 3, -1]])
# Define the vector
matrix_2 = np.array([4,19,7])
# Find the solution for the system of equations using the solve() method
x= np.linalg.solve(matrix_1, matrix_2)
print("The value of x1 is: ",x[0])
print("The value of x2 is: ",x[1])
print("The value of x3 is: ",x[2])


The value of x1 is:  3.0
The value of x2 is:  1.0
The value of x3 is:  2.0
